---
abstract: 'Simple diff to String'
author:
  - 'Kazuhiro Osawa <ko@yappo.ne.jp>'
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.760'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Diff
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Diff: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
